name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*" # Use the latest LTS version of Node.js

      # Install dependencies
      - name: Install dependencies
        run: npm ci # Ensures clean install from package-lock.json

      # Build the project
      - name: Build project
        run: npm run build

      # Upload production-ready build files as artifacts
      - name: Upload production files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Checkout the repository (if needed for deploy step)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download the build artifact from the previous step
      - name: Download build files
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      # Deploy to GitHub Pages or any other static hosting
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
